/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RsusOrEsop = IDL.Record({
  'stockName' : IDL.Text,
  'rate' : IDL.Float64,
  'quantity' : IDL.Float64,
});
export const MonthlySnapshot = IDL.Record({
  'fd' : IDL.Float64,
  'pf' : IDL.Float64,
  'nps' : IDL.Float64,
  'rsu' : RsusOrEsop,
  'goldRate' : IDL.Float64,
  'mutualFunds' : IDL.Float64,
  'month' : IDL.Nat,
  'usStocks' : IDL.Float64,
  'interest' : IDL.Float64,
  'homeLoan' : IDL.Float64,
  'esop' : RsusOrEsop,
  'silverGrams' : IDL.Float64,
  'year' : IDL.Nat,
  'goldGrams' : IDL.Float64,
  'silverRate' : IDL.Float64,
  'indianEquity' : IDL.Float64,
  'dividends' : IDL.Float64,
});
export const Portfolio = IDL.Record({
  'fd' : IDL.Float64,
  'pf' : IDL.Float64,
  'nps' : IDL.Float64,
  'rsu' : IDL.Float64,
  'mutualFunds' : IDL.Float64,
  'usStocks' : IDL.Float64,
  'interest' : IDL.Float64,
  'homeLoan' : IDL.Float64,
  'esop' : IDL.Float64,
  'gold' : IDL.Float64,
  'indianEquity' : IDL.Float64,
  'dividends' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAssets' : IDL.Float64,
          'totalLiabilities' : IDL.Float64,
          'netWorth' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getMonthlySnapshots' : IDL.Func([], [IDL.Vec(MonthlySnapshot)], ['query']),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMonthlySnapshot' : IDL.Func([MonthlySnapshot], [], []),
  'updatePortfolio' : IDL.Func([Portfolio], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RsusOrEsop = IDL.Record({
    'stockName' : IDL.Text,
    'rate' : IDL.Float64,
    'quantity' : IDL.Float64,
  });
  const MonthlySnapshot = IDL.Record({
    'fd' : IDL.Float64,
    'pf' : IDL.Float64,
    'nps' : IDL.Float64,
    'rsu' : RsusOrEsop,
    'goldRate' : IDL.Float64,
    'mutualFunds' : IDL.Float64,
    'month' : IDL.Nat,
    'usStocks' : IDL.Float64,
    'interest' : IDL.Float64,
    'homeLoan' : IDL.Float64,
    'esop' : RsusOrEsop,
    'silverGrams' : IDL.Float64,
    'year' : IDL.Nat,
    'goldGrams' : IDL.Float64,
    'silverRate' : IDL.Float64,
    'indianEquity' : IDL.Float64,
    'dividends' : IDL.Float64,
  });
  const Portfolio = IDL.Record({
    'fd' : IDL.Float64,
    'pf' : IDL.Float64,
    'nps' : IDL.Float64,
    'rsu' : IDL.Float64,
    'mutualFunds' : IDL.Float64,
    'usStocks' : IDL.Float64,
    'interest' : IDL.Float64,
    'homeLoan' : IDL.Float64,
    'esop' : IDL.Float64,
    'gold' : IDL.Float64,
    'indianEquity' : IDL.Float64,
    'dividends' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAssets' : IDL.Float64,
            'totalLiabilities' : IDL.Float64,
            'netWorth' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getMonthlySnapshots' : IDL.Func([], [IDL.Vec(MonthlySnapshot)], ['query']),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAuthenticated' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMonthlySnapshot' : IDL.Func([MonthlySnapshot], [], []),
    'updatePortfolio' : IDL.Func([Portfolio], [], []),
  });
};

export const init = ({ IDL }) => { return []; };