/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MonthlySnapshot {
  'fd' : number,
  'pf' : number,
  'nps' : number,
  'rsu' : RsusOrEsop,
  'goldRate' : number,
  'mutualFunds' : number,
  'month' : bigint,
  'usStocks' : number,
  'interest' : number,
  'homeLoan' : number,
  'esop' : RsusOrEsop,
  'silverGrams' : number,
  'year' : bigint,
  'goldGrams' : number,
  'silverRate' : number,
  'indianEquity' : number,
  'dividends' : number,
}
export interface Portfolio {
  'fd' : number,
  'pf' : number,
  'nps' : number,
  'rsu' : number,
  'mutualFunds' : number,
  'usStocks' : number,
  'interest' : number,
  'homeLoan' : number,
  'esop' : number,
  'gold' : number,
  'indianEquity' : number,
  'dividends' : number,
}
export interface RsusOrEsop {
  'stockName' : string,
  'rate' : number,
  'quantity' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<
    [],
    { 'totalAssets' : number, 'totalLiabilities' : number, 'netWorth' : number }
  >,
  'getMonthlySnapshots' : ActorMethod<[], Array<MonthlySnapshot>>,
  'getPortfolio' : ActorMethod<[], Portfolio>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAuthenticated' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMonthlySnapshot' : ActorMethod<[MonthlySnapshot], undefined>,
  'updatePortfolio' : ActorMethod<[Portfolio], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];